- hosts: remote
  gather_facts: false 
  vars_prompt:
    - name: packages
      prompt: Quels packages voulez vous installer ?
      private: no
'''  
  tasks:
    - name: install packages 
      package: 
        name: "{{ package }}" 
        state: present
'''

    - name: debug
      debug:
        msg:"{{ packages }}"
      

