- hosts: remote
  gather_facts: false 
  vars_prompt:
    - name: packages
      prompt: Quels packages voulez vous installer ?
      private: no
   
  tasks:
    - name: 
      set_fact:
       application_list: "{{ packages.split(',') }}"

    - name: debug1
      debug:
       msg: "{{ packages }}"
    - name: debug2
      debug:
       msg: "{{ item }}"
      loop: "{{ application_list }}" 

                        

