---
# tasks file for nic
- name: Create a network interface
  azure_rm_networkinterface:
    name: "{{ myNetworkInterface }}"
    resource_group: "{{ myResourceGroup }}"
    virtual_network: "{{ myVirtualNetwork }}"
    subnet_name: "{{ mySubnet }}"
    security_group: "{{ mySecurityGroup }}"
    ip_configurations:
      - name: default
        public_ip_address_name: "{{ myPublicIp }}"
        primary: True
